Repository sparta-tigers/sparta-tigers, pull requests merged in 2025-06, with the labels that each got.

#44 [라이브보드] 채팅 기능 개선
  build.gradle
  src/main/java/com/sparta/spartatigers/domain/liveboard/controller/LiveBoardMessageController.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/controller/LiveBoardRoomController.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/controller/LiveBoardStompController.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/dto/response/LiveBoardRoomResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/model/LiveBoardMessage.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/model/LiveBoardRoom.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/model/MessageType.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/pubsub/RedisMessagePublisher.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/pubsub/RedisMessageSubscriber.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/repository/LiveBoardRoomRepository.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/scheduler/LiveBoardScheduler.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/service/LiveBoardRoomService.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/service/LiveBoardService.java
  src/main/java/com/sparta/spartatigers/domain/match/model/entity/Match.java
  src/main/java/com/sparta/spartatigers/domain/match/repository/MatchRepository.java
  src/main/java/com/sparta/spartatigers/domain/team/model/entity/Team.java
  src/main/java/com/sparta/spartatigers/domain/team/repository/TeamRepository.java
  src/main/java/com/sparta/spartatigers/global/config/RedisConfig.java
  src/main/java/com/sparta/spartatigers/global/config/WebSocketConfig.java
Labels: feature

#45 [소셜로그인]소셜 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/sparta/spartatigers/domain/user/controller/AuthController.java
  src/main/java/com/sparta/spartatigers/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/AuthResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/CodeResDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/CustomUserPrincipal.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/spartatigers/domain/user/service/CustomOAuth2UserDetailsService.java
  src/main/java/com/sparta/spartatigers/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/global/config/SecurityConfig.java
  src/main/java/com/sparta/spartatigers/global/config/SocialLogin.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/filter/JwtFilter.java
  src/main/java/com/sparta/spartatigers/global/handler/OAuth2SuccessHandler.java
  src/main/java/com/sparta/spartatigers/global/util/JwtProperties.java
  src/main/java/com/sparta/spartatigers/global/util/JwtUtil.java
  src/main/resources/application-social.yml
  src/main/resources/application.yml
  src/main/resources/db.yml
Labels: feature

#48 [채팅방] 채팅방 목록 전체 조회 #10
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/DirectRoomController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/DirectRoomDto.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/repository/DirectRoomRepository.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/DirectRoomService.java
  src/main/resources/db.yml
Labels: feature, refactor

#50 [feat/item] 티켓 & 굿즈 목록 조회 구현
  src/main/java/com/sparta/spartatigers/domain/item/controller/ItemController.java
  src/main/java/com/sparta/spartatigers/domain/item/dto/response/ReadItemResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/item/repository/ItemRepository.java
  src/main/java/com/sparta/spartatigers/domain/item/repository/ItemRepositoryQuery.java
  src/main/java/com/sparta/spartatigers/domain/item/repository/ItemRepositoryQueryImpl.java
  src/main/java/com/sparta/spartatigers/domain/item/service/ItemService.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/UserResponseDto.java
Labels: feature

#54 [feat/item] 티켓 & 굿즈 상세 조회 구현
  src/main/java/com/sparta/spartatigers/domain/item/controller/ItemController.java
  src/main/java/com/sparta/spartatigers/domain/item/dto/response/ReadItemDetailResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/item/repository/ItemRepositoryQuery.java
  src/main/java/com/sparta/spartatigers/domain/item/repository/ItemRepositoryQueryImpl.java
  src/main/java/com/sparta/spartatigers/domain/item/service/ItemService.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
Labels: feature

#56 [feat/watchlist] 직관 기록 API 구현
  src/main/java/com/sparta/spartatigers/domain/match/dto/MatchScheduleDto.java
  src/main/java/com/sparta/spartatigers/domain/match/model/entity/Match.java
  src/main/java/com/sparta/spartatigers/domain/match/repository/MatchRepository.java
  src/main/java/com/sparta/spartatigers/domain/user/model/CustomUserPrincipal.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/controller/WatchListController.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/MatchDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/RecordDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/.gitkeep
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/CreateWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/SearchWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/UpdateWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/response/.gitkeep
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/response/CreateWatchListResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/response/WatchListResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/model/entity/WatchList.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListQueryRepository.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListQueryRepositoryImpl.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListRepository.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/WatchListService.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/exception/InvalidRequestException.java
Labels: feature

#60 [feat/exchange request] 티켓 & 굿즈 교환 API 구현
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/controller/ExchangeRequestController.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/request/UpdateExchangeRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/response/.gitkeep
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/response/ReceiveRequestResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/response/SendRequestResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/model/entity/ExchangeRequest.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/repository/ExchangeRequestQueryRepository.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/repository/ExchangeRequestQueryRepositoryImpl.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/service/ExchangeRequestService.java
  src/main/java/com/sparta/spartatigers/domain/item/model/entity/Item.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/response/MessageCode.java
Labels: feature

#61 [feat/favorite-team] 응원 팀 API 구현
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/controller/FavoriteTeamController.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/dto/request/FavTeamRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/dto/response/FavTeamResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/model/entity/FavoriteTeam.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/repository/FavoriteTeamRepository.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/service/FavoriteTeamService.java
  src/main/java/com/sparta/spartatigers/domain/team/repository/TeamRepository.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/CreateWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/response/CreateWatchListResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/model/entity/WatchList.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/WatchListService.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
Labels: feature

#66 [feat/watchlist] 직관 기록 통계 API 구현
  src/main/java/com/sparta/spartatigers/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/controller/WatchListController.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/response/StatsResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListRepository.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/StatsAccumulator.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/WatchListService.java
Labels: feature

#68 [채팅방] 채팅방 생성, 조회 로직 수정 #67
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/DirectRoomController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/DirectRoomDto.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/DirectRoomResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/model/entity/DirectRoom.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/repository/DirectRoomRepository.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/DirectRoomService.java
  src/main/java/com/sparta/spartatigers/global/config/SecurityConfig.java
Labels: feature, refactor

#69 [Refactor/login] CustomPrincipal 수정
  src/main/java/com/sparta/spartatigers/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/CustomUserPrincipal.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/spartatigers/domain/user/service/CustomOAuth2UserDetailsService.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/handler/OAuth2SuccessHandler.java
Labels: refactor

#76 [feat/chatmessage] 채팅 메시지 기능 구현 #12
  src/main/java/com/sparta/spartatigers/domain/chatroom/chat-tester.html
  src/main/java/com/sparta/spartatigers/domain/chatroom/config/RedisDirectRoomMessageSubscriberConfig.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/config/RedisUserSessionRegistry.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/config/StompAuthInterceptor.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/config/StompPrincipal.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/config/StompSessionEventListener.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/ChatMessageController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/request/ChatMessageRequest.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/ChatMessageResponse.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/pubsub/RedisDirectMessagePublisher.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/pubsub/RedisDirectMessageSubscriber.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/repository/DirectMessageRepository.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/ChatMessageService.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/DirectRoomService.java
  src/main/java/com/sparta/spartatigers/global/config/SecurityConfig.java
  src/main/java/com/sparta/spartatigers/global/config/WebSocketConfig.java
Labels: feature, docs, refactor

#81 [feat/exchange request] 교환 완료 시 채팅방 및 메시지 삭제 #79
  src/main/java/com/sparta/spartatigers/domain/chatroom/model/entity/DirectRoom.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/repository/DirectMessageRepository.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/repository/DirectRoomRepository.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/DirectRoomService.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/model/entity/ExchangeRequest.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/service/ExchangeRequestService.java
Labels: feature

#83 [feat/item] 거래 종료 시 위치 정보 삭제
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/service/ExchangeRequestService.java
  src/main/java/com/sparta/spartatigers/domain/item/service/LocationService.java
Labels: feature

#90 [refactor] 티켓 & 굿즈 위치 기능 개선
  src/main/java/com/sparta/spartatigers/domain/item/service/LocationService.java
  src/main/java/com/sparta/spartatigers/global/interceptor/AuthChannelInterceptor.java
Labels: fix

#84 [Feature] 알람 전송 및 CRUD
  src/main/java/com/sparta/spartatigers/SpartaTigersApplication.java
  src/main/java/com/sparta/spartatigers/domain/alarm/controller/AlarmController.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/request/AlarmDeleteDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/request/AlarmUpdateDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/response/AlarmInfo.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/response/AlarmResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/response/MatchDetailResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/response/MatchScheduleResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/response/TeamNameResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/model/entity/Alarm.java
  src/main/java/com/sparta/spartatigers/domain/alarm/redis/RedisAlarmPublisher.java
  src/main/java/com/sparta/spartatigers/domain/alarm/redis/RedisAlarmSubscriber.java
  src/main/java/com/sparta/spartatigers/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/sparta/spartatigers/domain/alarm/scheduler/AlarmScheduler.java
  src/main/java/com/sparta/spartatigers/domain/alarm/service/AlarmService.java
  src/main/java/com/sparta/spartatigers/domain/alarm/service/AlarmServiceImpl.java
  src/main/java/com/sparta/spartatigers/domain/match/repository/MatchRepository.java
  src/main/java/com/sparta/spartatigers/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartatigers/domain/user/service/Oauth2UserDetailsService.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/global/config/RedisConfig.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/response/MessageCode.java
Labels: feature

#94 [feature/login] 소셜 로그인 설정 추가, 일반 로그인 추가
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/response/ReceiveRequestResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/response/SendRequestResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/item/dto/response/ReadItemDetailResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/item/dto/response/ReadItemResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/AuthResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/CodeResDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/AuthResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/CodeResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/UserInfoResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/UserResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/global/config/SecurityConfig.java
  src/main/java/com/sparta/spartatigers/global/config/SocialLogin.java
  src/main/java/com/sparta/spartatigers/global/response/MessageCode.java
  src/main/resources/application-social.yml
Labels: feature

#97 [feat/directroom subscribe validator] 채팅 기능 코드 리팩토링, 유효성 검사 - #85 #96
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/ChatMessageController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/listener/DirectRoomSubscribeValidator.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/listener/StompSessionEventListener.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/model/security/StompPrincipal.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/pubsub/RedisDirectMessageSubscriber.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/registry/RedisUserSessionRegistry.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/DirectRoomService.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/interceptor/LiveBoardInterceptor.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/service/LiveBoardRedisService.java
  src/main/java/com/sparta/spartatigers/global/config/RedisDirectRoomMessageSubscriberConfig.java
  src/main/java/com/sparta/spartatigers/global/config/WebSocketConfig.java
  src/main/java/com/sparta/spartatigers/global/interceptor/StompAuthInterceptor.java
  src/main/resources/application.yml
Labels: feature, refactor

#95 [feature/login] 타소셜 로그인 구현 및 상태코드 예외 수정
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/request/AlarmRegisterDto.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/request/AlarmUpdateDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/CodeResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/CustomUserPrincipal.java
  src/main/java/com/sparta/spartatigers/domain/user/model/GoogleUserInfo.java
  src/main/java/com/sparta/spartatigers/domain/user/model/KakaoUserInfo.java
  src/main/java/com/sparta/spartatigers/domain/user/model/NaverUserInfo.java
  src/main/java/com/sparta/spartatigers/domain/user/model/OAuth2UserInfo.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/service/CustomOAuth2UserDetailsService.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/exception/InvalidRequestException.java
  src/main/java/com/sparta/spartatigers/global/exception/ServerException.java
  src/main/java/com/sparta/spartatigers/global/handler/OAuth2SuccessHandler.java
  src/main/java/com/sparta/spartatigers/global/response/ApiResponseAdvice.java
Labels: feature, refactor

#101 feat/direct message 채팅 기능 메시지 중복 수신 문제 해결 #100
  src/main/java/com/sparta/spartatigers/domain/chatroom/chat-tester.html
  src/main/java/com/sparta/spartatigers/domain/chatroom/registry/RedisUserSessionRegistry.java
Labels: feature

#108 feat/direct message 채팅 기능 redis 세션 관리 방법 변경 #103
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/DirectMessageController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/registry/RedisUserSessionRegistry.java
Labels: feature

#106 [feat/item] 야구장 근처에서만 티켓 & 굿즈 등록이 가능하도록 로직 추가
  src/main/java/com/sparta/spartatigers/domain/item/controller/ItemController.java
  src/main/java/com/sparta/spartatigers/domain/item/dto/request/CreateItemWithLocationRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/item/service/ItemService.java
  src/main/java/com/sparta/spartatigers/domain/item/service/LocationService.java
  src/main/java/com/sparta/spartatigers/domain/team/model/entity/Stadium.java
  src/main/java/com/sparta/spartatigers/domain/team/repository/StadiumRepository.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
Labels: feature

#109 [Feature] 유저 이미지 수정 및 삭제
  build.gradle
  src/main/java/com/sparta/spartatigers/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/ProfileResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/response/UserInfoResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/global/config/AwsS3Config.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/response/MessageCode.java
  src/main/java/com/sparta/spartatigers/global/util/FileUtil.java
  src/main/java/com/sparta/spartatigers/global/util/S3FolderType.java
  src/main/java/com/sparta/spartatigers/global/util/S3Properties.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: feature

#112 feat/direct message 채팅 기능 메시지 저장 로직 서비스로 분리 및 Redis 발행 구조 개선
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/ChatMessageController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/ChatMessageResponse.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/RedisMessage.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/pubsub/RedisDirectMessagePublisher.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/pubsub/RedisDirectMessageSubscriber.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/registry/RedisUserSessionRegistry.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/ChatMessageService.java
  src/main/java/com/sparta/spartatigers/global/config/RedisDirectRoomMessageSubscriberConfig.java
Labels: feature, refactor

#120 [feat/actions] CI/CD 권한 문제 해결
  .github/workflows/ci-cd.yml
Labels: feature

#124 [feat/health-check] 서버 상태 확인 엔드포인트 생성
  src/main/java/com/sparta/spartatigers/global/monitoring/HealthCheckController.java
Labels: feature

#125 feat/direct message 채팅방 목록 조회 시 상대방 접속 여부 로직 추가 및 응답 데이터 추가
  src/main/java/com/sparta/spartatigers/domain/chatroom/chat-tester.html
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/DirectRoomController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/controller/UserConnectController.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/DirectRoomCreateResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/dto/response/DirectRoomResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/repository/DirectRoomRepository.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/DirectRoomService.java
  src/main/java/com/sparta/spartatigers/domain/chatroom/service/UserConnectService.java
Labels: feature

#128 [refactor/watchlist] 직관 기록 도메인 리팩토링
  src/main/java/com/sparta/spartatigers/domain/watchlist/controller/WatchListController.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/MatchDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/RecordDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/CreateWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/UpdateWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/WatchListService.java
  src/main/java/com/sparta/spartatigers/global/response/MessageCode.java
Labels: refactor

#135 [Feature] Watchlist 및 S3 설정 추가 및 수정
  build.gradle
  src/main/java/com/sparta/spartatigers/domain/alarm/controller/AlarmController.java
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/request/AlarmRegisterDto.java
  src/main/java/com/sparta/spartatigers/domain/item/service/ItemService.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/controller/WatchListController.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/request/SearchWatchListRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/dto/response/CreateWatchListImageResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/model/entity/WatchList.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/model/entity/WatchListFile.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListFileRepository.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListQueryRepositoryImpl.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/scheduler/WatchListScheduler.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/WatchListService.java
  src/main/java/com/sparta/spartatigers/global/service/S3Service.java
  src/main/java/com/sparta/spartatigers/global/util/FileUtil.java
Labels: feature, fix, refactor

#138 [라이브 보드] 경기 중계 전송 기능
  src/main/java/com/sparta/spartatigers/domain/chatroom/listener/StompSessionEventListener.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/controller/LiveBoardRoomController.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/dto/response/LiveBoardRoomResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/model/GameMessage.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/model/GamePlayer.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/model/MatchScore.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/pubsub/LiveBoardMatchSubscriber.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/pubsub/LiveBoardMatchSubscriberConfig.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/repository/LiveBoardRoomRepository.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/service/LiveBoardRedisService.java
  src/main/java/com/sparta/spartatigers/domain/liveboard/service/LiveBoardRoomService.java
  src/main/java/com/sparta/spartatigers/global/handler/OAuth2SuccessHandler.java
Labels: feature

#140 [feat/item] 로그 관련 설정 추가 및 로직 수정
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/dto/response/ReceiveRequestResponseDto.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/repository/ExchangeRequestQueryRepository.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/repository/ExchangeRequestQueryRepositoryImpl.java
  src/main/java/com/sparta/spartatigers/domain/exchangerequest/service/ExchangeRequestService.java
  src/main/java/com/sparta/spartatigers/domain/item/service/ItemService.java
  src/main/java/com/sparta/spartatigers/domain/item/service/LocationService.java
  src/main/java/com/sparta/spartatigers/global/filter/LoggingTestController.java
  src/main/resources/logback-spring.xml
Labels: feature, fix, refactor

#143 [feat/CI-CD] task-definition 템플릿에 로깅 활성화
  aws/ecs/task-definition.json
Labels: feature

#142 [refactor/user] 로그 관련 설정 추가 및 로직 수정
  src/main/java/com/sparta/spartatigers/domain/alarm/controller/AlarmController.java
  src/main/java/com/sparta/spartatigers/domain/user/controller/UserController.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/request/UpdateNicknameRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/request/UpdatePasswordRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/repository/WatchListFileRepository.java
  src/main/java/com/sparta/spartatigers/domain/watchlist/service/WatchListService.java
  src/main/java/com/sparta/spartatigers/global/exception/ExceptionCode.java
  src/main/java/com/sparta/spartatigers/global/response/MessageCode.java
  src/main/resources/application-social.yml
Labels: feature, refactor

#148 [feat/CI-CD] 소셜 로그인 시 관련 환경변수 추가
  .github/workflows/ci-cd.yml
  aws/ecs/task-definition.json
Labels: feature
