Repository sparta-tigers/sparta-tigers, pull requests merged in 2025-07, with the labels that each got.

#164 [hotFix] 버그 수정
  src/main/java/com/sparta/spartatigers/domain/alarm/controller/AlarmController.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/controller/FavoriteTeamController.java
  src/main/java/com/sparta/spartatigers/domain/favoriteteam/service/FavoriteTeamService.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/request/LoginRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/sparta/spartatigers/domain/user/model/entity/User.java
  src/main/java/com/sparta/spartatigers/domain/user/service/UserService.java
  src/main/resources/application-s3.yml
Labels: bug, fix

#175 [hoxfix/alarm] Register Valid 수정
  src/main/java/com/sparta/spartatigers/domain/alarm/dto/request/AlarmRegisterDto.java
Labels: bug

#183 docs: 리드미 작업
  README.md
  readme/image/ci.webp
  readme/image/cloud.webp
  readme/image/erd.webp
Labels: docs
